# Generated by Django 5.2.4 on 2026-01-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipattempt',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ipattempt',
            name='status',
            field=models.CharField(choices=[('CLEARED', 'CLEARED'), ('SUSPICIOUS', 'SUSPICIOUS'), ('BLOCKED', 'BLOCKED')], default='CLEARED', max_length=20),
        ),
    ]
