# Generated by Django 5.2.4 on 2026-01-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_ipattempt_last_seen_ipattempt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipattempt',
            name='last_risk',
        ),
        migrations.AlterField(
            model_name='ipattempt',
            name='status',
            field=models.CharField(default='CLEARED', max_length=20),
        ),
    ]
